import { Provider } from "@/components/ui/provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html
            lang="en"
            suppressHydrationWarning
        >
            <body className={`${geistSans.className} `}>
                <Provider
                    enableSystem
                    defaultTheme="system"
                    attribute="data-theme"
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster />
                </Provider>
            </body>
        </html>
    );
};

export default Layout;
